const B = require('../js/render.js'); const assert = require('assert'); let n = 0; const ok = (c, m) => { assert(c, m); n++; };
const evil = { displayName: '<img src=x onerror=alert(1)>', bio: '"><script>alert(1)</script>', avatar: 'javascript:alert(1)', banner: "https://x/a.png') ; background:url(evil", links: [{ title: 'ok', url: 'https://ok.example' }, { title: 'js', url: 'javascript:alert(1)' }, { title: 'data', url: 'data:text/html,hi' }, { title: '<b>t</b>', url: 'example.com/path' }], socials: [{ type: 'evil', url: 'https://s.example' }], design: { btnColor: 'red;}body{display:none', font: 'comic', spacing: -50, preset: 'nope' }, youtube: { q: '@chan' } };
const h = B.renderProfile(evil, { username: 'voqcl' });
ok(!/<script>alert/.test(h) && !/<img src=x/.test(h) && !h.includes('javascript:') && !h.includes('data:text'), 'no injected markup or unsafe URLs');
ok(h.includes('https://ok.example') && h.includes('https://example.com/path') && h.includes('&lt;b&gt;t&lt;/b&gt;'), 'safe links kept, bare domain upgraded to https, titles escaped');
ok(!h.includes('display:none') && !h.includes("background:url(evil"), 'CSS injection blocked');
const p = B.normalize(evil); ok(p.avatar === '' && p.banner === '' && p.design.spacing === 4 && p.design.font === 'sans' && p.socials[0].type === 'website' && p.youtube.q === '@chan' && p.youtube.show, 'normalize clamps/validates');
const y = B.renderYoutube({ id: 'UC1', title: '<x>', avatar: 'https://a/b.jpg', subscribers: 1234567, videoCount: 10, url: 'javascript:1', videos: [{ id: 'abcdefghijk', title: 'V<1>', thumb: 'https://t/1.jpg' }, { id: 'bad id"><', title: 'x' }] });
ok(y.includes('1.2M subscribers') && y.includes('&lt;x&gt;') && !y.includes('javascript:') && y.includes('watch?v=abcdefghijk') && !y.includes('bad id'), 'YouTube block: compact stats, escaping, bad ids dropped');
ok(B.renderYoutube(null, 'error', 'Nope <b>').includes('Nope &lt;b&gt;'), 'YouTube error state escaped');
ok(B.renderParts({ youtube: { q: '@c', show: false } }).body.indexOf('id="yt"') === -1, 'YouTube hidden when show=false');
ok(B.renderProfile({ banner: 'https://cdn.example/b.png' }).includes('class="bn"'), 'banner rendered');
ok(B.normalize({ avatar: 'data:image/png;base64,iVBORw0KGgo=' }).avatar.startsWith('data:image/png'), 'embedded PNG avatar allowed');
ok(B.normalize({ avatar: 'data:image/svg+xml;base64,PHN2Zz4=' }).avatar === '' && B.normalize({ banner: 'data:text/html,hi' }).banner === '', 'SVG / non-image data URLs rejected');
const ex = B.exportBioHtml({ displayName: 'N', bio: 'x</script><script>alert(1)</script>', links: [{ title: 't', url: 'https://a.b' }] }, { username: 'voqcl' });
ok(!/<script>alert/.test(ex) && ex.includes('<link rel="canonical" href="https://voqcl.com/bio/voqcl">') && ex.includes('src="../config.js"') && ex.includes('og:title'), 'exported page: no script injection, canonical voqcl.com/bio/voqcl, OG tags, relative scripts');
const back = B.parseBioHtml(ex); ok(back && back.username === 'voqcl' && back.data.bio.startsWith('x</script>') && back.data.links.length === 1, 'exported page round-trips back into the editor');
ok(B.parseBioHtml('<html>nope</html>') === null && B.parseBioHtml('<script type="application/json" id="voqcl-bio">{"username":"Bad Name!","data":{}}</script>') === null, 'foreign / tampered files rejected');
console.log(`render: ${n} assertions passed`);
